#define JSON_TOK_STRING                  1
#define JSON_TOK_COL                     2
#define JSON_TOK_COMMA                   3
#define JSON_TOK_LBRACK                  4
#define JSON_TOK_RBRACK                  5
#define JSON_TOK_LSQB                    6
#define JSON_TOK_RSQB                    7
#define JSON_TOK_NUMBER                  8
#define JSON_TOK_BOOLEAN                 9
#define JSON_TOK_NONE                   10
